procs:
  ---- vS-Graphs ----:
    shell: ''
    autostart: false
  vS-Graphs RGB-D:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash && 
      source ~/workspace/install/setup.bash && 
      ros2 launch vs_graphs rgbd.launch.py"'
    autostart: false
  vS-Graphs RGB-D-IMU:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash && 
      source ~/workspace/install/setup.bash && 
      ros2 launch vs_graphs rgbd-imu.launch.py"'
    autostart: false

  ---- Procedures ----:
    shell: ''
    autostart: false
  Build vS-Graphs:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash && 
      source ~/workspace/install/setup.bash && cd ~/workspace &&
      colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-select vs_graphs"'
    autostart: false

  ---- Tools ----:
    shell: ''
    autostart: false
  Voxblox Client:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash && 
      python ~/workspace/vsgraphs_tools/relay_jazzy.py --mode voxblox_client"'
    autostart: false
  PointCloud Server:
    shell: 'bash -c "source /opt/ros/jazzy/setup.bash && 
      python ~/workspace/vsgraphs_tools/relay_jazzy.py --mode pc_server"'
    autostart: false